### ISSUE TITLE
Submission could not be found

### ISSUE THREAD

**Issue by AshStuff** [waymo-research/waymo-open-dataset#153]
Hello,
I submitted the validation predictions to the server and the it got uploaded successfully but when I open the submission I get `submission could not found` and I waited for 5 hours to check back, still the same result.

Here is the screenshot
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/9457497/81025238-9b6c4480-8e3b-11ea-8563-a678d702c712.png">

**Comment by peisun1115** [comment]
Did you limit number of predictions per frame? Usually it takes too long to compute because of that.

**Comment by AshStuff** [comment]
I actually uploaded the validation ground truth to the server to do a sanity check, so the perditions per frame should be the actual number of perditions.

**Comment by peisun1115** [comment]
Thanks for reporting this. Can you check again? I cannot check on my own as i do not know which is your account

**Comment by AshStuff** [comment]
Thanks. I am getting `No submission information` when I tried now. I also tried offline with `create_submission` in `metrics/tools` and it ran without any error. How do I view the result saved under say `/tmp/mymodel` ?

**Comment by peisun1115** [comment]
Read this issue if you have not seen it https://github.com/waymo-research/waymo-open-dataset/issues/148#issuecomment-620201129

If that does not solve the issue, make sure [these two](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/submission.txtpb#L5-L7) are set.

If it still fails (should not happen), you can examine the tar.gz file on your own. It is simply a serialized proto of [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/submission.proto#L26)

Something like:

f = open('your_untared_submission_file')
s = waymo_open_dataset.protos.Submission()
CHECK(s.ParseFromString(f.read()))
f.close()
print(s)

**Comment by linlu-qiu** [comment]
I'm having similar issues. I was able to get the evaluation results from server before. I used the same steps to create my submission, but I failed to get the results this time. I have the account name and method name included.

**Comment by peisun1115** [comment]
The server was overloaded and it is fixed now.

**Comment by fuhuan26** [comment]
@peisun1115 I just submitted the validation set and it is still showing the message below after half an hour. Is the server okay?
![image](https://user-images.githubusercontent.com/50088717/82847661-3dfc6e00-9ea4-11ea-846c-2d91c9a63d86.png)

**Comment by peisun1115** [comment]
It should be fixed now. The results should be ready soon.

**Comment by fuhuan26** [comment]
> It should be fixed now. The results should be ready soon.

It works now. Thanks!
