### ISSUE TITLE
ImportError: cannot import name 'py_camera_model_ops' from 'waymo_open_dataset.camera.ops' (unknown location)

### ISSUE THREAD

**Issue by ZLTJohn** [waymo-research/waymo-open-dataset#487]
I followed the [quick_start](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md) to install this project to my server via 

> pip3 install waymo-open-dataset-tf-2-6-0 --user

But when running the new [tutorial_camera_only.ipynb](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_camera_only.ipynb) I got an error. The code and error is listed below:

> from waymo_open_dataset import dataset_pb2 as open_dataset
> from waymo_open_dataset import label_pb2
> from waymo_open_dataset.camera.ops import py_camera_model_ops

> ImportError: cannot import name 'py_camera_model_ops' from 'waymo_open_dataset.camera.ops' (unknown location)

I spent a lot of time to check my environment but found nothing. Finally I compared the site-package directory with the original project, and there is no such file named 'py_camera_model_ops.py' in directory
> anaconda3/envs/waymo132/lib/python3.7/site-packages/waymo_open_dataset/camera

The problem is solved by copying the very same file from source into the  package. But I wonder whether it's my environment's fault or there is something wrong in the pip package?

**Comment by hfslyc** [comment]
Hi,

Thanks for reporting this bug. The issue is fixed in pip package 1.4.8.

Thanks,
Wayne, on behalf of the Waymo Open Dataset team.

**Comment by tdzdog** [comment]
@alexgorban， However, I have installed waymo-open-dataset-tf-2-6-0 with 1.4.9, such problem is not solved.

**Comment by SPA-junghokim** [comment]
Same issue in the newest git version (12th, Nov, 2023).
And the method of "[ZLTJohn](https://github.com/ZLTJohn)" can solve the same issue for me. Thanks.
